version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the path-filtering orb is required to continue a pipeline based on
# the path of an updated fileset
orbs:
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  # the always-run workflow is always triggered, regardless of the pipeline parameters.
  always-run:
    jobs:
      # the path-filtering/filter job determines which pipeline
      # parameters to update.
      - path-filtering/filter:
          name: check-updated-files
          # 3-column, whitespace-delimited mapping. One mapping per
          # line:
          # <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>
          mapping: |
            api-gateway/.* api-gateway true
            cloudfront/.* cloudfront true
            cloudwatch/.* cloudwatch true
            cluster-1-eksctl/.* cluster-1-eksctl true
            dynamodb/.* dynamodb true
            ec2/.* ec2 true
            ecr/.* ecr true
            efs/.* efs true
            elasticache/.* elasticache true
            iam/.* iam true
            kinesis/.* kinesis true
            lambda/.* lambda true
            rc-production/.* rc-production true
            rds/.* rds true
            route53/.* route53 true
            s3/.* s3 true
            sqs/.* sqs true
            vpc/.* vpc true
          base-revision: master
          # this is the path of the configuration we should trigger once
          # path filtering and pipeline parameter value updates are
          # complete. In this case, we are using the parent dynamic
          # configuration itself.
          config-path: .circleci/continue_config.yml
