version: 2.1

parameters:
  api-gateway:
    type: boolean
    default: false

jobs:
  foo:
    docker:
      - image: cimg/base:2022.08
    steps:
      - when:
          condition: << pipeline.parameters.api-gateway >>
          steps:
            - checkout
            - run: echo "The job for api-gateway is runing"

workflows:
  build-run:
    jobs:
      - foo
