version: 2.1

parameters:
  api-gateway:
    type: boolean
    default: false

jobs:
  build-api-gateway:
    docker:
      - image: cimg/base:current
    steps:
      - when:
          condition: << pipeline.parameters.api-gateway >>
          steps:
            - checkout
            - run: echo "The job for api-gateway is runing"

workflows:
  build-run:
    jobs:
      - build-api-gateway
